### PR TITLE
Add Debian 11 support

### PR DESCRIPTION
**Pull request by toozej**
Adds Debian 11 support, and updates the version of monitoring-plugins installed to the latest current v2.3.1 per https://www.monitoring-plugins.org/download.html

Signed-off-by: James Tooze <toozej@gmail.com>

### CODE REVIEW

**Comment by GwennG** [comment]
Debian 11 bullseye has been released in August and is now largely deployed.
Will this patch be merged soon? There has been no release of this asset since nearly 2 years :-(

**Comment by toozej** [comment]
FWIW @GwennG I've largely moved over to the Sensu Golang-based equivalents to these monitoring-plugins also due to the lack of maintenance on this repo. 

Ones like:
- https://bonsai.sensu.io/assets/sensu/check-cpu-usage
- https://bonsai.sensu.io/assets/sensu/check-memory-usage
- https://bonsai.sensu.io/assets/sensu/check-disk-usage

**Comment by GwennG** [comment]
> FWIW



> FWIW @GwennG I've largely moved over to the Sensu Golang-based equivalents to these monitoring-plugins also due to the lack of maintenance on this repo.

I've already switched most checks to other assets but I did not find any equivalent to some checks from this package.

**Comment by jspaleta** [comment]
I'm looking to prep a release for this so I'll be merging this in soon. But yes in general, if we can get golang replacements built it would be easier to maintain.

While its possible to maintain assets that involve runtime detected C libraries, its a significant burden to keep up with linux distribution targets.

statically compiled anything ends up being easier, hence the preference to build in golang if the intent is to have asset packages.

**Pull request merged**
